# Generated by Django 5.1.15 on 2026-05-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
