# Generated by Django 5.1.15 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_caption_ar_property_caption_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='enrichment_confidence',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('NONE', 'NONE')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='land_registration_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('SALE', 'SALE'), ('RENT', 'RENT')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notary_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sarouty_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='scrape_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SCRAPED', 'SCRAPED'), ('ENRICHED', 'ENRICHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='yakeey_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
