# Generated by Django 5.1.15 on 2026-05-19 12:53
import base64

from django.db import migrations, models


def _short_code(uuid_value):
    return base64.b32encode(uuid_value.bytes[:5]).decode("ascii").rstrip("=").lower()[:6]


def backfill_short_codes(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    for prop in Property.objects.filter(short_code=""):
        prop.short_code = _short_code(prop.id)
        prop.save(update_fields=["short_code"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_area_alter_property_built_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_code',
            field=models.CharField(blank=True, default="", help_text="Public short URL slug — auto-derived from the property's UUID.", max_length=12),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_short_codes, noop_reverse),
        migrations.AlterField(
            model_name='property',
            name='short_code',
            field=models.CharField(blank=True, help_text="Public short URL slug — auto-derived from the property's UUID.", max_length=12, unique=True),
        ),
    ]
