# Generated by Django 5.1.15 on 2026-05-17 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def populate_agency_slug_and_updated_at(apps, schema_editor):
    """Populate slugs and updated timestamps before enforcing constraints."""
    Agency = apps.get_model("agencies", "Agency")
    used_slugs = set(
        Agency.objects.exclude(slug__isnull=True)
        .exclude(slug="")
        .values_list("slug", flat=True)
    )

    for agency in Agency.objects.all().order_by("created_at", "id"):
        base_slug = slugify(agency.name) or "agency"
        slug = base_slug
        counter = 2
        while slug in used_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1
        used_slugs.add(slug)
        agency.slug = slug
        agency.updated_at = agency.created_at or timezone.now()
        agency.save(update_fields=["slug", "updated_at"])


def create_user_table_if_missing(apps, schema_editor):
    """Create the custom user table for databases that already applied 0001."""
    User = apps.get_model("agencies", "User")
    existing_tables = schema_editor.connection.introspection.table_names()
    if User._meta.db_table not in existing_tables:
        schema_editor.create_model(User)


def drop_user_table_if_present(apps, schema_editor):
    """Reverse helper for the custom user table compatibility operation."""
    User = apps.get_model("agencies", "User")
    existing_tables = schema_editor.connection.introspection.table_names()
    if User._meta.db_table in existing_tables:
        schema_editor.delete_model(User)


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='propertyfinder_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(
            populate_agency_slug_and_updated_at, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_user_table_if_missing, drop_user_table_if_present
                )
            ],
            state_operations=[],
        ),
    ]
