# Generated by Django 5.1.15 on 2026-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_slug_agency_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='sarouty_agency_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='sarouty_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='total_listings',
            field=models.IntegerField(default=0),
        ),
    ]
