# Generated by Django 5.1.15 on 2026-05-17 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_slug_agency_subscription_expires_at_and_more'),
        ('properties', '0002_property_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_events', to='agencies.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_events', to='properties.property')),
            ],
            options={
                'verbose_name': 'Lead Event',
                'verbose_name_plural': 'Lead Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('click_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('map', 'Map'), ('share', 'Share')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_clicks', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Click',
                'verbose_name_plural': 'Property Clicks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property View',
                'verbose_name_plural': 'Property Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyAnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to='agencies.agency')),
                ('top_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_in_agency_summaries', to='properties.property')),
            ],
            options={
                'verbose_name': 'Agency Analytics Summary',
                'verbose_name_plural': 'Agency Analytics Summaries',
                'ordering': ['-date', 'agency__name'],
                'unique_together': {('agency', 'date')},
            },
        ),
    ]
