# Generated by Django 5.1.15 on 2026-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadevent',
            name='channel',
            field=models.CharField(blank=True, db_index=True, help_text='Where they came from: instagram / facebook / tiktok / youtube / direct', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyclick',
            name='channel',
            field=models.CharField(blank=True, db_index=True, help_text='instagram / facebook / tiktok / youtube / direct etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='channel',
            field=models.CharField(blank=True, db_index=True, help_text='instagram / facebook / tiktok / youtube / direct etc. (from utm_source or referrer)', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadevent',
            name='source',
            field=models.CharField(help_text='How they contacted: call / whatsapp / email', max_length=50),
        ),
    ]
