# Generated by Django 5.1.15 on 2026-05-17 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_agency_slug_agency_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pages_visited', models.IntegerField(default=0)),
                ('agencies_found', models.IntegerField(default=0)),
                ('agencies_new', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Collection Run',
                'verbose_name_plural': 'Collection Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectedAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('city_raw', models.CharField(blank=True, max_length=120)),
                ('propertyfinder_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('source_url', models.URLField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('matched_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_propertyfinder_records', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Collected Agency',
                'verbose_name_plural': 'Collected Agencies',
                'ordering': ['-collected_at'],
            },
        ),
    ]
