# Generated by Django 5.1.15 on 2026-05-17 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_caption_ar_property_caption_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=150, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='properties.property')),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['platform', 'status'], name='social_soci_platfor_3dc017_idx'), models.Index(fields=['scheduled_at'], name='social_soci_schedul_193f50_idx')],
            },
        ),
    ]
